I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 13, in script
IOError: Couldn't find file 'picva_dragon.jpg'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\execution.py", line 294, in run
    node.execute()
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\ast.py", line 464, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\exports.py", line 925, in say
    who(what, interact=interact)
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\character.py", line 812, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\character.py", line 678, in do_display
    **display_args)
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\character.py", line 481, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\ui.py", line 237, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\display\core.py", line 1993, in interact
    repeat, rv = self.interact_core(preloads=preloads, **kwargs)
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\display\core.py", line 2311, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\display\core.py", line 1530, in draw_screen
    renpy.config.screen_height,
  File "render.pyx", line 365, in renpy.display.render.render_screen (gen\renpy.display.render.c:5300)
  File "render.pyx", line 166, in renpy.display.render.render (gen\renpy.display.render.c:2491)
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\display\layout.py", line 536, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 95, in renpy.display.render.render (gen\renpy.display.render.c:2764)
  File "render.pyx", line 166, in renpy.display.render.render (gen\renpy.display.render.c:2491)
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\display\layout.py", line 536, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 95, in renpy.display.render.render (gen\renpy.display.render.c:2764)
  File "render.pyx", line 166, in renpy.display.render.render (gen\renpy.display.render.c:2491)
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\display\layout.py", line 536, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 95, in renpy.display.render.render (gen\renpy.display.render.c:2764)
  File "render.pyx", line 166, in renpy.display.render.render (gen\renpy.display.render.c:2491)
  File "accelerator.pyx", line 109, in renpy.display.accelerator.transform_render (gen\renpy.display.accelerator.c:1654)
  File "render.pyx", line 166, in renpy.display.render.render (gen\renpy.display.render.c:2491)
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\display\image.py", line 164, in render
    return wrap_render(self.target, width, height, st, at)
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\display\image.py", line 54, in wrap_render
    rend = render(child, w, h, st, at)
  File "render.pyx", line 95, in renpy.display.render.render (gen\renpy.display.render.c:2764)
  File "render.pyx", line 166, in renpy.display.render.render (gen\renpy.display.render.c:2491)
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\display\im.py", line 463, in render
    im = cache.get(self)
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\display\im.py", line 196, in get
    surf = image.load()
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\display\im.py", line 507, in load
    surf = renpy.display.pgrender.load_image(renpy.loader.load(self.filename), self.filename)
  File "H:\Development\RenPy\renpy-6.15.7-sdk\renpy\loader.py", line 428, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'picva_dragon.jpg'.

Windows-7-6.1.7601-SP1
Ren'Py 6.17.3.327
Defiler Wings 0.0.1
